### ISSUE TITLE
Zorganizujmy się!

### ISSUE THREAD

**Issue by wnadurski** [Motoryka/Gra#1]
Hej, jako typek od infrastruktury bawię się trochę naszym nowym repo :) Sprawdzam nowe funkcje. Rozpoczynam tym postem dyskusje w celu zorganizowania się! Dyskutujmy o tym, co to znaczy :D 

Magdalena Foks - menadżer projektu
Jeżyna Domańska - dokumentacja
Mateusz Nojek - kontrola jakości
Wojciech Nadurski - infrastruktura

Proponuje ustalić jakieś coding guidelines :), środowisko w którym będziemy pracować i.. cos jeszcze?

**Comment by wnadurski** [comment]
Ogarnę jak się gitem poslugiwac i zrobie jakiegos tutka

**Comment by wnadurski** [comment]
odkrylem, ze unity w wersji free pozwala na wymuszenie zapisywania assetow w formacie tekstowym - nawet sceny. Git wiec bedzie do tego spoko, bedzie mozna mergowac :)

**Comment by magdafox** [comment]
Brawo Łysy !

To może też dobre miejsce na spisanie notatek z piątkowego spotkania. Jak Jeżyna wrzuci co zanotowała, zobaczymy co mamy ważnego do ustalenia na początek :)

**Comment by jezyna** [comment]
To co zapisałam na spotkaniu z Landowską:
*mamy ustalić plan działania
*na pracę którą oddamy ma się skladać plan, raport końcowy (kto i co zrobił), dokumentacja (dotycząca zarówno procesu jak i produktu), instrukcja dla użytkownika, przewodnik po implementacji oraz ewaluacja
*dokumentować na bieżąco kto i co zrobił
*całość będzie do oddania do początku grudnia

Poza tym mam zanotowane że ośrodek zaopatruje się teraz w 7-calowe Samsungi Galaxy Tab 3 oraz zapisany adres mailowy tego chłopaka który robił analogiczną pracę - msmiatacz@gmail.com.

**Comment by wnadurski** [comment]
Jak mam zrobic konto pani Landowskiej?

**Comment by magdafox** [comment]
Hasło i login można po prostu wymyślić.
Ale nie wiem co z mailem. Coś jeszcze jest potrzebne ?

**Comment by wnadurski** [comment]
maila pg moze, co?

**Comment by magdafox** [comment]
Chyba tak.
Jesli chcesz, moge napisac - zapytac.

**Comment by wnadurski** [comment]
Stworzyłem p. Landowskiej konto
Login: "nailie"
e-mail: "nailie@eti.pg.gda.pl"
haslo "motoryka1"

I zaprosilem do naszej organizacji do grupy Observers. Jak możesz, to jako lider wyślij p. Landowskiej maila :)

**Comment by magdafox** [comment]
Mail wysłany :)

**Comment by magdafox** [comment]
"Witam,

o 11:30 kończę zajęcia, więc proponuję 11:35 albo 12.

Pozdrawiam,
Agnieszka Landowska"

Dobrze - odpowiedziała.
Źle - problem z terminem. Może 11:35 + spóźnimy sie na zajęcia i oddamy na końcu ?

**Comment by wnadurski** [comment]
mamy 40 minut do zajec wiec nie jest tak zle.

**Comment by magdafox** [comment]
Okej, jutro 11:35 !

**Comment by nojas10** [comment]
11.35 u Landowskiej (odpisała)?
Jeśli tak, to ja proponuję z 15min szybciej się spotkać żeby omówić "wspólną wersję". :)

**Comment by magdafox** [comment]
Tak, tak jak wcześniej mówiliśmy 15 minut na dyskusje :)

Czyli bądźmy jutro ok. 11:20.

**Comment by nojas10** [comment]
Niech Jeżyna spisze te najważniejsze postanowienia, a ja zamykam to issue, bo już jest po terminie Milestone 1.
