### ISSUE TITLE
Trening z Unity3d

### ISSUE THREAD

**Issue by wnadurski** [Motoryka/Gra#10]
Jako, że działamy w Unity przydałoby się trochę podszkolić z koszystania z tego silnika. Polecam zrobić tutoriale ze strony unity. RogueLike - ten jest bardzo spoko dla gier 2d i uczy troche pisania na mobilki.

Możemy się również spotkać i mogę coś Wam pokazać, to co umiem. Ale umiem nie zawiele :D Terminy?

**Comment by nojas10** [comment]
W przyszłym tygodniu mogę codziennie po 17. :)

**Comment by magdafox** [comment]
Może jakoś wtorek po zajęciach / wieczorem ?

**Comment by magdafox** [comment]
Ja w sumie jak Mati, oby nie piątek ;P

**Comment by nojas10** [comment]
Mi pasuje. Łysy?

**Comment by wnadurski** [comment]
wtorek ale wieczorem bo jestem w pracy

**Comment by magdafox** [comment]
Wstępnie jutro (wtorek) ok. 19:00 ?

**Comment by nojas10** [comment]
Wolałbym wcześniej. jestem wolny od 17.30. Łysy, ja też w pracy i możesz ze mną wracać / jechać do Wrzeszcza.

**Comment by magdafox** [comment]
Jeżyna ma korki do 18:30, ja chyba też w pracy. No nie wiem, jak uważacie. Ewentualnie jestem wolna w środe już po WZR, czyli po 14 do wieczora.

**Comment by jezyna** [comment]
poprzesuwałam korki, powinny się skończyć 17, maks. 17:30. Możemy się umówić na 18, jeżeli bym kończyła o 17:30 to się spóźnię ale to was uprzedzę. A gdzie?

**Comment by wnadurski** [comment]
Może u mnie? BO poczebuję kompa

**Comment by jezyna** [comment]
zabierać kompy?

**Comment by wnadurski** [comment]
tak :)

**Comment by wnadurski** [comment]
I uprzedzam, że tka bardzo nie ogarniam unity, i programuję zazwyczaj googlami :D
