### ISSUE TITLE
Projekt gry - planowanie sprintu

### ISSUE THREAD

**Issue by nojas10** [Motoryka/Gra#11]
Musimy w końcu zacząć robić naszą grę. W końcu zrobiło się luźniej na uczelni i następne koło mamy za 2 tygodnie. Warto teraz coś zacząć, więc może spotkamy się i rozplanujemy nasz projekt i nakreślimy jego koncepcję? 
Piszcie kiedy Wam pasuje. 
Ja mogę:
2.06 - po godz. 17
3.06 - po godz. 17
5.06 - też jakoś tam mogę
weekend też

**Comment by wnadurski** [comment]
tak

**Comment by magdafox** [comment]
Tak. Co do terminu - może pn (8.06) po zajęciach ?
Długi weekend może być ciężko nas zgrać tak mi się wydaje. A w pn kończymy dosyć wcześnie.

**Comment by nojas10** [comment]
Mi poniedziałek pasuje, ale mam ED 14-15. A tak to spoko :)

**Comment by magdafox** [comment]
No właśnie tak myślałam po waszym ED. My mamy KSR do 14.

**Comment by wnadurski** [comment]
ok

**Comment by nojas10** [comment]
Przypominam, że jutro się widzimy :)

**Comment by magdafox** [comment]
Macie dziś ED ? Mam prośbę, jeśli nie, możemy zacząć o 14 ? Lub jeśli skończycie wcześniej, zacząć od razu jak wyjdziecie?

**Comment by nojas10** [comment]
Mamy ED, ale możemy zacząć od razu po, tak myślę.

**Comment by wnadurski** [comment]
Dodawalem Was do Youtracka

**Comment by wnadurski** [comment]
https://wnadurski.myjetbrains.com/

**Comment by wnadurski** [comment]
Jezyna: login: jezyna.domanska,
Magda: Magda.foks

Wyslalem Wam maile weryfikujace. Jezyna nawet potwierdzila :P

**Comment by nojas10** [comment]
Niech ktoś wprowadzi nasz sprint na agile boards i zrobi porządek ;d.
Ale w sumie... raczej się nie wyrobimy, więc albo olewamy ten sprint i rozpoczniemy go na nowo w lipcu, albo przenosimy wszystko do backloga i mamy słaby sprint review, a potem przeniesiemy taski do kolejnego sprintu. Ja przez poprawę z BSK nie mam czasu teraz się niczym innym zająć :(

**Comment by magdafox** [comment]
Ja tak samo BSK. Będzie ciężko ukończyć ten sprint.

**Comment by jezyna** [comment]
Chciałam sprint wprowadzić ale nie miałam jeszcze dostępu do youtracka, wszystko co było ustalone jest za to wrzucone na gita od jakiegoś czasu już.

U mnie też nie ma szansy się wyrobić, proponowałabym przerzucić to na lipiec.
