### ISSUE TITLE
Wielojęzyczność

### ISSUE THREAD

**Issue by wnadurski** [Motoryka/Gra#12]
Mówiłem już Nojasowi: co myślicie, żeby zrobić naszą grę wielojęzyczną? Żeby ludzie mogli jej używać na całym świecie!

To znaczy, zrobilibyśmy w jednym języku, ale stworzyli łatwy do obsługi moduł językowy, który pozwalałby łatwe dodawanie nowych tłumaczeń. Co myślicie?

**Comment by jezyna** [comment]
bardzo spoko pomysł. I pewnie nie będzie trudno o tłumaczenia, bo w grze nie będzie raczej trudnych zwrotów

**Comment by wnadurski** [comment]
To do tego proponuję pisać kod i dokumentację kodu w języku angielskim, żeby może kiedyś kto znajdzie sobie repo na githubie mógłby dalej rozwijać projekt. Dokumentację dotyczącą realizacji projektu chyba możemy dalej pisać w polskim, bo to potrzebne nam tylko do projektu inżynierskiego. 

OPEN SOURCE GÓRO
