### ISSUE TITLE
PathAnalyser problem z trojkatem

### ISSUE THREAD

**Issue by wnadurski** [Motoryka/Gra#13]
Analizator zakonczenia gry nie ogarnia trojkata

**Comment by magdafox** [comment]
Nie ogarnia, bo sprawdzane są wygenerowane wierzchołki (czy ludek przejechał przez wierzchołek), w momencie gdy są zamknięte figury z jednego punktu musimy zacząć i też tam skończyć.

Dorobiłam też sprawdzanie czy zaczynamy i kończymy w odpowiednim wierzchołku, ale to póki co słabo działa, bo nie są oznaczone wierzchołki początkowe, więc właściwie użytkownik nie wie gdzie zacząć żeby było poprawnie (ciężko skończyć grę).

Wydaje mi się że po dorobieniu zabezpieczenia, żeby zaczynać z odpowiedniego wierzchołka wystarczy dodatkowe sprawdzenie czy koniec naszej linii też jest w odpowiednim miejscu.

**Comment by magdafox** [comment]
jest ok
