### ISSUE TITLE
Generator ksztaltow

### ISSUE THREAD

**Issue by wnadurski** [Motoryka/Gra#14]
Generator generuje:
- za krotkie pojedyncze linie (czasami)
- ciagle ta sama linie falista
- trojkaty, ktorych prawie nei widac

**Comment by nojas10** [comment]
* Linie proste nie są już za krótkie 
* Linia krzywa jest wybierana losowo spośród 12 (na razie tyle) predefiniowanych
* Trójkąty poprawione, lecz wymagają jeszcze dopracowania

**Comment by nojas10** [comment]
Wszystkie kształty dobrze się rysują.
