### ISSUE TITLE
Config Loader - problem z deserializacja na Androidzie

### ISSUE THREAD

**Issue by wnadurski** [Motoryka/Gra#16]
proba deserializacji configa na androdzie wywoluje totalny rozpizdziel gry. Funkcja nie zwraca nulla, ani nic, tylko wywala caly obiekt, ktory uzyj funkcji. Gra sie dalej toczy i sa bez przerwy null pointery bo, nie ma obiektu, ktory zostal rozwlaony.

Dodac jakas obsluge wyjatkow i zwracac nulla, proponuje.

**Comment by nojas10** [comment]
Config Loader działa.
