### ISSUE TITLE
Logika wykrywania punktu startowego

### ISSUE THREAD

**Issue by nojas10** [Motoryka/Gra#17]
Zdarza się, że jak np. w kwadracie zacznę w punkcie początkowym i przejadę przez jeden wierzchołek, a następnie wrócę do początku i jeszcze gdzieś pomacham to zaliczy mi poziom nawet jeśli nie skończę w punkcie końcowym (bo wcześniej go odwiedziłem).

**Comment by magdafox** [comment]
Logika wykrywania punktu startowego to coś innego - to kwestia ustalenia czy dany punkt to początek kształtu.

To o czym piszesz na pewno zdarza się nie tylko w kwadracie, ale w każdej figurze. Tak zostało zaimplementowane. Funkcja sprawdzająca czy zakończyć rysowanie mówi o tym, czy dany kształt został z daną dokładnością zamalowany (nie sprawdzam tam gdzie kończymy rysowanie figury).

I tu jest kwestia ustalenia - sama ciągle nie wiem jak to ostatecznie powinno działać! Jeżeli dodamy sprawdzanie punktu końcowego też może być irytujące jeżeli się pomylimy w trakcie rysowania, ale domalujemy resztkę figury, a poziom mimo wszystko się nie zakończy (chociaż cała figura jest zamalowana)! Ja bym jeszcze zobaczyła jak to będzie wyglądać podczas rysowania kilku linii (z przerywaniem).

**Comment by magdafox** [comment]
Tego chyba nie robimy co ? Zakończenie rysowania w konkretnym punkcie.

**Comment by nojas10** [comment]
Nie, nie robimy.
