### ISSUE TITLE
Animacje

### ISSUE THREAD

**Issue by nojas10** [Motoryka/Gra#18]
Czy można te rybki (dotyczy to też startowej) trochę upiększyć? Dać im jakąś jeszcze może płetwę grzbietową, jakiś uśmiech czy coś takiego? No i ta sfochowana chyba jednak powinna być szczęśliwa, a nie obrażona :P

**Comment by magdafox** [comment]
Ratujmy sfochowaną rybę ! :P

**Comment by nojas10** [comment]
<po przemyśleniach> Brakuje mi sfochowanej ryby :(

**Comment by jezyna** [comment]
Wczesniej pisaliście że nie ma być zła! :p ale dobrze, można ja wrócić ;p

**Comment by nojas10** [comment]
Ja mówię tylko, że mi brakuje, nie wiem jak reszcie :P
