### ISSUE TITLE
Wykrywanie zakończenia rysowania

### ISSUE THREAD

**Issue by nojas10** [Motoryka/Gra#19]
Gdy aplikacja uzna poziom za zaliczony to automatycznie przerywa możliwość rysowania. Trochę to irytuje, bo teraz tolerancja zakończenia jest zwiększona i kończy nawet jak nie dojedziemy do tego końca. Może by tak zrobić jakąś informację na ekranie, że udało się zaliczyć (jakaś gwiazdka, napis brawo, zmiana koloru, nie wiem), a dopiero po oderwaniu palca lub po np. 2s gdy nie przestanie się rysować ukazywana jest animacja i przejście do kolejnego etapu?

**Comment by wnadurski** [comment]
Wcześniej zrobiłem, ze nie przerywa rysowania i tez było dziwnie, bo dopiero po chwili gra się przełączała i nie było wiadomo, czy się udało czy nie.

**Comment by jezyna** [comment]
a może zrobić tak że przerywa rysowanie w momencie jak przejedzie punkt końcowy? albo wyłączyć rysowanie sekundę po osiągnięciu zadanej dokładności czy coś

**Comment by magdafox** [comment]
Przrywanie w momencie przejechania przez punkt końcowy nic nie da - w sumie tak to działa mniej więcej, tyle że jak jest ustawiony większy zakres błędu to zanim przejedziemy przez koniec już uznaje że wszystkie wierzchołki są "zaliczone" z odpowiednią dokładnością.

Nie wiem, możemy ewentualnie jeszcze spróbować trochę wydłużyć czas po jakim gra się kończy od momentu stwierdzenia że IsFinished().
