### ISSUE TITLE
Unity3d vs tanie tablety

### ISSUE THREAD

**Issue by wnadurski** [Motoryka/Gra#2]
# Wymagania unity
http://unity3d.com/unity/system-requirements - ze strony: wymagania zaleza od zlozonosci gry, oprocz tego:
Android: OS 2.3.1 or later; ARMv7 (Cortex) CPU or Atom CPU; OpenGL ES 2.0 or later.

Szukając informacji o tabletach biedronkowych, prawie każdy ma androida > 4. Znalazlem na allegro jednego z 2.3 (nie wiem czy pojdzie). Najtanszy tablet biedronkowy http://allegro.pl/tablet-mytab-7-wifi-my-tab-7-7-cali-4gb-sklep-i5177126285.html <- procesor jakis chinski, ale podobno (znalazlem na wikipedii) ma rdzen Cortex . http://allegro.pl/tablet-canox-pc-755-n-7-polecam-i5214775714.html <- tani tablet, ktory ma tego calego cortexa. Moze kupimy jakies na spole do testow, co? 

Ogolnie to patrzylem, to wiekszosc tabletow ma rdzenie ARM, malo (moze tych tanich) Intela (atom).

**Comment by wnadurski** [comment]
Co robimy? Wedlug mnie unity jest ok, tymbardziej ze kupuja galaxy. Mozemy na spotkaniu dowiedziec sie jakie modele tabletow maja i przejrzec ich specyfikacje.

**Comment by magdafox** [comment]
Czyli jesteśmy za unity, dowiemy się więcej o ich tabletach na spotkaniu i sprawdzimy.
Zgadza się ?

**Comment by wnadurski** [comment]
inwestujemy w jakiegos taniego?

**Comment by nojas10** [comment]
Jak dla mnie appkę trzeba robić na androida 4.0+. A jeśli chodzi o zakup tableta to ja jestem otwarty. Te 50zł na osobę to nie majątek, a będziemy mieli na czym testować ;)

**Comment by wnadurski** [comment]
Tez mysli ze te 50 dych ok, ostatnio trafilem 3 w totka.

**Comment by jezyna** [comment]
Spoko, mogę się dorzucić :) Tylko kupując trzeba pamiętać że najlepiej żeby miał ten wymiar co te ich, czyli 7 cali

**Comment by wnadurski** [comment]
oki :)

**Comment by magdafox** [comment]
Ok, tez dorzuce jak uzbieram :)

**Comment by wnadurski** [comment]
przetestowalismy moja pseudo gre w unity na tablecie matiego i dziala
