### ISSUE TITLE
Dźwięk pomyślnie zakończonego

### ISSUE THREAD

**Issue by nojas10** [Motoryka/Gra#24]
Pojawia się nawet, kiedy pominiemy poziom.
Powinien też być odtwarzany trochę wcześniej - w momencie kiedy gra zostaje uznana za zaliczoną, tak proponuję.

**Comment by magdafox** [comment]
Poprawione.
Mati potwierdź czy OK :)

**Comment by nojas10** [comment]
Własnie sprawdziłem. Jest git :)

**Comment by wnadurski** [comment]
Ja też to poprawiałem xD

**Comment by magdafox** [comment]
Tak :P poprawiłeś pierwszą część buga xD 
niestety i tak to przerabiałam ze wzgl na druga ;p
