### ISSUE TITLE
Konfigurowanie czasu rysowania

### ISSUE THREAD

**Issue by nojas10** [Motoryka/Gra#25]
Czas, w którym można jeszcze kontynuować rysowanie bez przerwania poziomu nie jest konfigurowalny - zawsze ta sama wartość zostaje w zapisanej konfiguracji.

**Comment by wnadurski** [comment]
Naprawione w 95710f56b1a9612e9f00d6a961858333c05f73cc @wnadurski wnadurski committed 27 minutes ago

**Comment by nojas10** [comment]
Działa
