### ISSUE TITLE
Źle zaznaczona konfiguracja w oknie wyboru

### ISSUE THREAD

**Issue by nojas10** [Motoryka/Gra#26]
Po zapisaniu konfiguracji (i w innych przypadkach) aktualnie zmieniana konfiguracja nie jest wczytana i podświetla się inna, a czasem kilka innych (sprawdza po nazwie i nie bierze pod uwagę id, a także zaznacza button poprzez zmianę jego koloru - może spróbować łapać focus?).

**Comment by nojas10** [comment]
Gdy konfiguracja jest wczytana, a wchodzimy do Opcji poprzez ekran główny to nie wyświetla się przycisk Edytuj.

**Comment by nojas10** [comment]
Powinna też być nazwa Opcje wyświetlana, aby wiedzieć, gdzie się znajdujemy.

**Comment by wnadurski** [comment]
przyciski wbudowanych poziomow są źle zrobiony - ich prostokąty są duże większe niż obrazki i najeżdzają się na siebie, przez co nie można wcisnąć odpowiednich przycisków

**Comment by jezyna** [comment]
naprawione przyciski łatwy/średni/trudny, spójrzcie czy spoko czy coś jeszcze nie styka

**Comment by nojas10** [comment]
Na jakim branchu?
