### ISSUE TITLE
Narzędzia - acunote/youtrack

### ISSUE THREAD

**Issue by magdafox** [Motoryka/Gra#3]
Do weryfikacji i przetestowania :)

**Comment by nojas10** [comment]
Tzn. mam zrobić sobie konto i się pobawić czy jak?

**Comment by wnadurski** [comment]
Assignee: wnadurski, ale jak chcesz mozesz przepisac na siebie

**Comment by magdafox** [comment]
No tak, myślałam że wszystko idzie na Wojtka. Dogadajcie sie :)
To jest darmowe wgl ?

**Comment by wnadurski** [comment]
Acunote dla teamow do 5 osob tak.

**Comment by nojas10** [comment]
Polecam sprawdzić też YouTrack od JetBrains. Ja tego używam i jest przyjemne i darmowe do 10 osób. Porównaj i oceń, Łysy.

**Comment by wnadurski** [comment]
AcuNote moze polaczyc z repo na githubie, widziec commity i tworzyc code review. Czy chcemy cos takiego? Czy w YouTrack jest taka opcja?

**Comment by nojas10** [comment]
Da się:
https://www.jetbrains.com/youtrack/features/integrations.html

**Comment by nojas10** [comment]
Eee... zalogowałem się na tego Acunote - brzydkie to.
YouTrack dużo bardziej przejrzysty :)

**Comment by wnadurski** [comment]
YouTrack:
- bardziej skomplikowany
- ładniejszy
- możliwości integracji z GitHubem, na zasadzie zamykanie/tagowanie issue w YouTracku poprzez komendy wpisane w danym commicie
- brak review kodu commitow gita

AcuNote:
- brzydki
- troche chyba bardziej toporny
- mozliwosc integracji z githubem
- review commitow z gita

Co wybieramy

**Comment by wnadurski** [comment]
Ja głosuję za youtrackiem :d

**Comment by nojas10** [comment]
Ja też za YouTrackiem.

**Comment by jezyna** [comment]
nie używałam nigdy żadnego z nich, ale z tego co googlowałam YouTrack ma też aplikację na telefon a AcuNote nie, poza tym rzeczywiście jest ładniejszy, więc może być YouTrack :d
