### ISSUE TITLE
Dodanie opcji do wybory kolorów

### ISSUE THREAD

**Issue by nojas10** [Motoryka/Gra#34]
Powinna być opcja wyboru losowego koloru (poza czarnym), która będzie wczytana domyślnie podczas dodawania nowego poziomu.

**Comment by wnadurski** [comment]
Nie robiłbym tego. Ewentualnie przy dodowaniu poziomu może losować się kolor

**Comment by nojas10** [comment]
A ja bym zrobił. Jak się dodaje nowy level to powinny być koloru domyślne, a nie że gra narzuci jakiś konkretny. Czemu byś tego nie robił?

**Comment by nojas10** [comment]
Dobra, zrobię na razie tak jak mówisz, bo ta zmiana co wymyśliłem jednak nie jest taka prosta.

**Comment by wnadurski** [comment]
Właśnie dlatego bym nie robił, bo to będzie generowało bugi :P

**Comment by nojas10** [comment]
Zrobione tak, że losuje się kolor przy generowania konfiguracji albo poziomu do konfiguracji.
