### ISSUE TITLE
[Config] Zaznaczonych wiele róznych konfigów na raz

### ISSUE THREAD

**Issue by wnadurski** [Motoryka/Gra#37]
![Multiple configs bug](http://snag.gy/EqNmv.jpg)

Kroki do reproduikcji:
1. Wejście do menu opcji
2. Kliknięcie Dodaj nowy
3. Zapisanie o domyślnej nazwie.
4. Wybranie z listy konfigu Nazwa
5. Kliknięcie dodaj nowy
6. Zapisanie o domyślnej nazwie
7. Przy okienku pytającym "Czy napewno?" odpowiedzieć "Tak, napewno"

**Comment by wnadurski** [comment]
Co ciekawe, te dw aconfigy później są tak jakby tym samym. Edytując jeden, edytuję drugi.

**Comment by nojas10** [comment]
Został tylko problem z zaznaczeniem konfiguracji, ale to będzie zintegrowane jeszcze z grafikami i będzie działać.

**Comment by jezyna** [comment]
nie wiem czy też tak macie, ale u mnie jak wejdę w to podmenu config to domyślnie lista konfiguracji jest pusta mimo że mam stworzone dwie. Dopiero jak wejdę w dodaj a potem wrócę do configa klikając anuluj to lista się zapełnia. Tak jakby się nie odświeżała na starcie

**Comment by wnadurski** [comment]
ja tka nie mam

**Comment by nojas10** [comment]
No możesz nie mieć plików tam gdzie być powinny. Domyślnie są w takiej lokalizacji:
C:\Users\nojas_000\AppData\LocalLow\Motoryka\fms_v0_X\configs (tam gdzie X to musi być numerek z ustawień buildu). A jeśli już dodałaś raz konfiguracje i potem wyłączyłaś grę i włączyłaś to już są (bo powinny)?

**Comment by nojas10** [comment]
Już działa.
