### ISSUE TITLE
Nazewnictwo linii

### ISSUE THREAD

**Issue by nojas10** [Motoryka/Gra#39]
Mamy pewien problem z nazewnictwem. Ciężko tak od razu intuicyjnie stwierdzić co jest linią, a co kształtem lub śladem. Linia chyba bardziej kojarzy się z czymś prostym, śladem chyba można nazwać to, co zostawiamy mażąc palcem. Ja na początku stosowałem koncepcję, że "kształt" to to, co się wyrysowuje na ekranie automatycznie, a "linia" to, co rysujemy palcem, ale to nie jest do końca takie oczywiste. Co myślicie, ja kto nazwać? Może macie swoje propozycje? Bo w konfiguracji trzeba to jakoś podpisać.

**Comment by jezyna** [comment]
Wydaje mi się że 'kształt' i 'ślad' są najlepsze. Bo 'linia' rzeczywiście może podchodzić pod obie rzeczy.

**Comment by magdafox** [comment]
No chyba tak, ślad będzie lepszy niż linia.
