### ISSUE TITLE
Zakup tableta :D

### ISSUE THREAD

**Issue by wnadurski** [Motoryka/Gra#4]
Jak wyzej

**Comment by nojas10** [comment]
Mam szukać i zamawiać?
Najpierw sprawdźmy jaki oni mają sprzęt i wtedy coś wybiorę.

**Comment by wnadurski** [comment]
spoko, niech task wisi

**Comment by wnadurski** [comment]
Nojas ma jakiegos tableta i Marcin Salnik ma tableta jakiegos slabego i mowi ze moglby nam sprzedac.
Podal narazie cene 50 zl ale nie wiem czy w sumie nie bedzie chcial wiecej, bo to tablet jego dziewczyny xD ale mysle ze max 100.

**Comment by nojas10** [comment]
Zapomniałeś dodać, że ma nieproporcjonalne wymiary wyświetlacza i jest beznadziejnie słaby (ten Salnika). A mój może się przyda ;)

**Comment by wnadurski** [comment]
jest 7 calowy, ale dziwna rozdzielczosc. To ze jest slaby to ok, oni tez maja slabe podobno :P

**Comment by nojas10** [comment]
Ale podobno już mają (albo będą mieć) Galaxy Tab III, więc to jest niebo a ziemia ;)

**Comment by wnadurski** [comment]
Nom. Tylko pewnie i tak beda korzystac nadal ze starych. A jak bedzie chodzilo na slabym, to na dobrym tymbardziej :)

**Comment by magdafox** [comment]
Nojas, ogarnij się. Coz Tobą. Rób coś. i ty łysy też. Nic nie robisz.

**Comment by magdafox** [comment]
Cieniasy!

**Comment by nojas10** [comment]
Dobra, jak na razie możemy używać mojego tableta. Nie jest wyśmienity, ale trochę lepszy niż biedronkowe. Jest polskiej firmy Pentagram, ma 7 calowy ekran. Wklejam ponownie link do parametrów: http://www.pentagram.pl/produkty/tab-7-dot-6
Odpaliliśmy już z Łysym na nim prostą aplikację napisaną w Unity i działa bezbłędnie. Taki tablet powinien nam wystarczyć. Jeśli ktoś będzie go chciał do domu żeby porobić testy to bez problemu udostępnię - w domu leży i się kurzy od ponad roku (ostatnio mamie wgrałem zdjęcia z mojego dzieciństwa i sobie ogląda, ale raczej nie będzie miała problemu z rozstaniem :P )

**Comment by wnadurski** [comment]
Wiesz co Magda...

**Comment by wnadurski** [comment]
Zostajemy z tym co mamy
