### ISSUE TITLE
NIepotrzebna instancja UIConfigManager

### ISSUE THREAD

**Issue by nojas10** [Motoryka/Gra#40]
UIConfigManager niepotrzebnie woła metodę Init już w GameManagerze na początku aplikacji. Powinien się tworzyć dopiero, gdy go wołamy poprzez przycisk edycji (lub dodania) konfiguracji. Wtedy powinien tworzyć ekran dla przekazanego mu configa, a nie zawsze brać tego, który już jest w GameManagerze. Wynika to z tego, że jak tworzymy nową konfigurację, ale jej potem nie zapiszemy, to i tak niepotrzebnie tworzymy obiekt tej konfiguracji, a potem znów musimy stworzyć obiekt domyślnej konfiguracji, jeśli anulujemy zmiany (nie mamy wtedy też żadnej referencji np. na wcześniej zaznaczoną konfigurację i musimy wczytać jakąś z ConfigFactory). Workflow jest taki: Wchodzimy w Opcje, zaznaczamy jakąś konfigurację, dodajemy nową plusikiem, Anulujemy zmianę i zatwierdzamy wyjście, jesteśmy znowu w opcjach i wracając do nich nie możemy zaznaczyć poprzednio wybranej konfiguracji tylko musimy robić zaznaczenie np. na poziom Łatwy.

**Comment by wnadurski** [comment]
Gdzie UIConfigManager woła metodę Init?
UIConfigManager jest włożony do sceny config i nigdzie nie jest instancjonowany, nie może więc nic robić na początku aplikacji.

Do sceny konfiguracji wybrany (lub stworzony nowy) trzeba jakoś przekazać, a jedynym sposobem na przekazanie obiektu ze sceny do sceny jest umeiszczenie go w obiekcie, który nie jest niszczony przy przejściu ze sceny, np. GameManager. 

Kiedy się wybierze konfig i kliknie edytuj, to dokładnie ten obiekt jest przekazany do sceny konfiguracji. Czemu ma tak nie być?

**Comment by nojas10** [comment]
Ok, rozwiązałem to w taki sposób, że przed tworzeniem nowej konfiguracji zapamiętuję starą i jeśli nie dojdzie do zapisu nowej konfiguracji to wczytuję tamtą z powrotem jako obecną konfigurację.
