### ISSUE TITLE
[Scena wyników] nie poprawnie wyświetlane napisy

### ISSUE THREAD

**Issue by wnadurski** [Motoryka/Gra#41]
Przy ustawionym rozmiarze okna WSVGA (1024x600):
![Bug](http://snag.gy/QQqnt.jpg)

napis WYBIERZ jest ucięty

HVGA Landscape (480x320):
![Kolejny bug](http://snag.gy/UrH0d.jpg)

Nie ma napisu wybierz, liczby poziomów w dropdownie są niewidoczne.

**Comment by wnadurski** [comment]
![Bug](http://snag.gy/UNU8s.jpg)

Znikają informacje o kształcie i inne widoczne na screenie. Prawdopodobnie są za długie? Bo obiekt ShapeText ma wartość pola Text "Linia pozioma"

**Comment by nojas10** [comment]
Tych błędów jest więcej. Jak odpaliłem na smartfonie to też mi sporo napisów zwariowało, albo są strasznie małe, albo w ogóle ich nie ma na ekranie.

**Comment by jezyna** [comment]
no, tam było dużo więcej porozjeżdżane, wydaje mi się że wychwyciłam wszystko.
