### ISSUE TITLE
[Menu konfiguracji] Nie poprawne zaznaczanie konfiguracje

### ISSUE THREAD

**Issue by wnadurski** [Motoryka/Gra#42]
I. Obserwowane zachowanie:
Gdy mam wybrany jeden stworzony konfig, to gdy zmienie zaznaczenie na łatwy, średni lub trudny, tamten i ta pozostaje zaznaczony.

Kroki do reprodukcji:
1. usunąć wszystkie konfigi
2. Stworzyć nowy i zapisać
3. Zmienić zaznaczanie na łatwy

![Bug](http://snag.gy/kDfPi.jpg)

II. Obserwowane zachowanie:
Jeśli istnieje już jeden konfig, nie można go zaznaczyć (nie jest na zielono)

Kroki do reprodukcji:
1. wszystkie poprzednie kroki
2. Wyłączyć grę i włączyć
3. Wejść do ekranu konfiguracji
4. Wybrać stworzony konfig

**Comment by nojas10** [comment]
Już naprawiłem. Niechcący usunąłem linijki, które wydały mi się zbędne wcześniej. Zaraz wrzucam na mastera.
