### ISSUE TITLE
nie można kliknąć w początek linii

### ISSUE THREAD

**Issue by jezyna** [Motoryka/Gra#43]
Jeżeli początek linii (to chyba tylko przy liniach ukośnych się zdarza) wypadnie na napisie 'poziom 1/x' to nie można zacząć rysować.
![bug](https://cloud.githubusercontent.com/assets/11587453/11529582/4f8a2e2a-98ee-11e5-9c93-5026bb8b57c5.png)

**Comment by nojas10** [comment]
Naprawione.
