### ISSUE TITLE
Narzędzia - ReSharper

### ISSUE THREAD

**Issue by nojas10** [Motoryka/Gra#5]
JetBrains zrobił ukłon w stronę uczniów i udostępnił paczkę swoich narzędzi za darmo w celach edukacyjnych - wystarczy uzupełnić formularz na stronie:
https://www.jetbrains.com/estore/students/
W odpowiedzi na maila politechnicznego dostaniecie link do akceptacji, który trzeba użyć w ciągu 3 dni.  Zaakceptować regulamin, podać nick i hasło i gotowe - mamy licencję na rok. Teraz tylko ściągnąć ReSharpera. :)

**Comment by wnadurski** [comment]
ReSharper to rozszerzenie Visual Studio, służy do ułatwiania pisania kodu. Polecam go, ale chyba nie ma sensu ustanawiać go jakimś naszym standardem. Nie każdy musi u nas korzystać z Visual Studio. No i pewnie ogarnięcie go nie jest jakieś skomplikowane, ogranicza się do wyuczenia skrótów klawiszowych. Według mnie powinniśmy to zostawić ludziom do wyboru :)
