### ISSUE TITLE
Słownik pojęć

### ISSUE THREAD

**Issue by nojas10** [Motoryka/Gra#6]
Chciałbym, aby każdy z nas zaznajomił się z pojęciami, których znajomość jest nam niezbędna do zrozumienia tematu i odpowiedniego podejścia do odbiorcy naszego produktu (szczególnie podczas rozmów). Te pojęcia to m.in.: motoryka mała, autyzm. Później podrzucę Wam tu linki do artykułów oraz jeszcze inne pojęcia, które uznam za ważne.

**Comment by nojas10** [comment]
Linki do motoryki małej:
http://kreatywnik.bloog.pl/id,333700582,title,Mala-motoryka-czyli-na-czym-polega-usprawnianie-dloni-i-palcow-malego-smyka,index.html (szczególnie przeczytać do pierwszego przykładu ćwiczeń)
http://www.pm155.szkoly.lodz.pl/wp-content/uploads/10_rozwijanie_malej_motoryki.pdf (tu natomiast macie duży spis różnych ćwiczeń na rozwój motoryki małej)
Linki do autyzmu:
http://pl.wikipedia.org/wiki/Autyzm_dzieci%C4%99cy (standardowo przejrzeć wiki)
http://www.dzieci.bci.pl/strony/autism/czymjest.htm (to jest niedługie i ciekawe)

Fajnie jakby każdy z nas miał chociaż minimalne pojęcie na te tematy, więc zachęcam do czytania.

**Comment by wnadurski** [comment]
pracuj a nie
