### ISSUE TITLE
Lista pytań na spotkanie

### ISSUE THREAD

**Issue by nojas10** [Motoryka/Gra#7]
Trzeba zrobić listę potencjalnych pytań do opiekunów dzieci w Instytucie na środę 15.04. Myślę, że mogą to robić np. 2 osoby wspólnie, a reszta nawet może podsyłać pomysły na pytania. 
Mamy też przygotować listę czynności, które można przełożyć na wykonanie ich na tablecie oraz takich, których raczej się nie da (bo może komuś coś przyjdzie do głowy). Kto chętny?

**Comment by magdafox** [comment]
Zaraz się zajmę tą listą czynności. Mogę podjąć się spisania wszystkiego co ustalimy.

Listę wrzucę tu jak tylko coś już napisze. Zachęcam do uzupełnienia jej o wasze propozycje.
Co do pytań. Przede wszystkim każdy powinien zapoznać się z tematem "Słownik pojęć" :-) Może wszystkie pytania i wątpliwości wpisujcie też tutaj ?

**Comment by magdafox** [comment]
MALOWANIE / RYSOWANIE:

	-dużych kształtów
	-jednocześnie obydwiema rękami
	-linii prostych
	-linii splątanych (dom ślimaka)
	-krótkich, pionowych kresek
	-linii falujących (np. fale na morzu) z zachowaniem kierunku pisma
	-labiryntów
	-okrążanie elementów
	-krążenie między elementami
	-rysowanie prostych kształtów bez odrywania ręki
	-tworzenie szlaczków z elementów
	-dorysowanie brakujących elementów
	
KOLOROWANIE:

	-zamalowanie większych płaszczyzn konturowych - ruchy od lewej i prawej oraz z góry na dół
	-pól pomiędzy liniami poziomymi
	-obrazków
	-kropkowanie rysunków

KREŚLENIE ("po śladzie"):

	-linii poziomych i pionowych
	-linii kolistych i falistych
	-linii zamkniętych (koła, owale, prostokąty)
	-odwzorowywanie szlaczków i wzorów
	
UKŁADANIE:

	-układanie klocków
	-układanie puzzli
	-dopasowywanie kształtów
	-układanie całości z części, konstruowanie kształtów (klocki, figury złożyć w konkretną formę)
	-podział elementów według cech (kwadraty do kwadratów itp.)
	
INNE:

	-łączenie kropek
	-przyciskanie konkretnych miejsc na ekranie
	
	-naśladowanie gry na pianinie / pisania na maszynie
	-wycinanie różnych kształtów
	-wydzieranie
	-stemplowanie
	-dekorowanie
	-odtwarzanie rytmu deszczu
