### ISSUE TITLE
Ustalenie terminu spotkania z grupami

### ISSUE THREAD

**Issue by nojas10** [Motoryka/Gra#9]
Czy każdemu z Was został udostępniony kalendarz? Mi niby tak, ale nie widzę tam terminów innych osób i w sumie nie za bardzo rozumiem, o co chodzi w tym kalendarzu. Musimy ustalić jakiś termin, który pasuje w większości. Z każdej grupy musi być min. 2 przedstawicieli. Na spotkaniu mają być wszystkie 3 grupy zajmujące się aplikacjami dla IWRD, pani dr Landowska oraz Michał Smiatacz.

**Comment by jezyna** [comment]
U mnie kalendarz też jest pusty. Chyba wyślę do tej dziewczyny maila że z kalendarzem coś jest nie tak i żeby nam po prostu podała kilka pasujących terminów i się wypowiemy kiedy możemy być.

**Comment by magdafox** [comment]
Termin spotkania : 21.04.15 (wtorek) godzina 15:00 sala EA633.
